version: "3.8"

services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root321
      - MONGO_INITDB_DATABASE=db
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - mongo-server
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    networks:
      - mongo-server
    command: npm run start:dev

volumes:
  mongodb-data:
    name: mongodb-data
networks:
  mongo-server:
    driver: bridge
